### ISSUE TITLE
Add badge/info for branch type

### ISSUE THREAD

**Issue by xkamil** [tommwrobel/service-status-dashboard#9]
As user I want to know what type of branch is deployed. There are 3 possibilities:
- release branch:  regex: 'release/*"
- development branch: name of this branch is specified for each service in config under GET /api/envs-config
- feature/bugfix branch: every other branch

**Comment by tommwrobel** [comment]
desired design:
![image](https://user-images.githubusercontent.com/57330987/188815827-4e41caa2-7954-46c7-b6dd-e0779de1dddc.png)
prod/master: green
develop: blue
feature/bug etc: yellow
MUI component: https://mui.com/material-ui/react-chip/
